* [33mc0cbe38[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m)[m Prepare deployment config without secrets
[31m|[m * [33m0893d24[m[33m ([m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m)[m readme update
[31m|[m[31m/[m  
* [33m21d9661[m Add YOLO vision puzzle processing structure
* [33mc872283[m Add session plans, payments, assignments, classes, chat, and fix JS TDZ crash
*   [33m3cc99d9[m Merge branch 'main' of https://github.com/trixnity/FYP-v1.0.1
[33m|[m[34m\[m  
[33m|[m * [33mc3625c6[m README.md
[33m|[m * [33m27d7d6d[m README.md
[33m|[m * [33m2d40f1a[m Initial commit
* [33md8df9be[m Initial commit for FYP v1.0.1
