spring.application.name=fyp
spring.datasource.url=jdbc:mysql://localhost:3306/fypdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
stockfish.path=C:\\Users\\Surface Laptop 4\\Downloads\\Stockfish-master\\Stockfish-master\\src\\stockfish.exe
puzzles.import.path=C:\\Users\\Surface Laptop 4\\OneDrive\\Documents\\Sem 7\\FYP1\\db csv untuk retrieval\\lichess_db_puzzle.csv
